
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.cfgObj
{
/// <summary>
/// 通用属性配置表
/// </summary>
public partial class AttributeObj
{
    private readonly System.Collections.Generic.Dictionary<int, resource.AttributeResource> _dataMap;
    private readonly System.Collections.Generic.List<resource.AttributeResource> _dataList;
    
    public AttributeObj(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, resource.AttributeResource>();
        _dataList = new System.Collections.Generic.List<resource.AttributeResource>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            resource.AttributeResource _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.resource.AttributeResource.DeserializeAttributeResource(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, resource.AttributeResource> DataMap => _dataMap;
    public System.Collections.Generic.List<resource.AttributeResource> DataList => _dataList;

    public resource.AttributeResource GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public resource.AttributeResource Get(int key) => _dataMap[key];
    public resource.AttributeResource this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

