
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.cfgObj
{
/// <summary>
/// 通用子弹配置表
/// </summary>
public partial class BulletObj
{
    private readonly System.Collections.Generic.Dictionary<int, resource.BulletResource> _dataMap;
    private readonly System.Collections.Generic.List<resource.BulletResource> _dataList;
    
    public BulletObj(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, resource.BulletResource>();
        _dataList = new System.Collections.Generic.List<resource.BulletResource>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            resource.BulletResource _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.resource.BulletResource.DeserializeBulletResource(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, resource.BulletResource> DataMap => _dataMap;
    public System.Collections.Generic.List<resource.BulletResource> DataList => _dataList;

    public resource.BulletResource GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public resource.BulletResource Get(int key) => _dataMap[key];
    public resource.BulletResource this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

