
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.cfgObj
{
/// <summary>
/// 敌机子弹配置表
/// </summary>
public partial class EnemyBulletObj
{
    private readonly System.Collections.Generic.Dictionary<int, resource.EnemyBulletResource> _dataMap;
    private readonly System.Collections.Generic.List<resource.EnemyBulletResource> _dataList;
    
    public EnemyBulletObj(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, resource.EnemyBulletResource>();
        _dataList = new System.Collections.Generic.List<resource.EnemyBulletResource>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            resource.EnemyBulletResource _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.resource.EnemyBulletResource.DeserializeEnemyBulletResource(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, resource.EnemyBulletResource> DataMap => _dataMap;
    public System.Collections.Generic.List<resource.EnemyBulletResource> DataList => _dataList;

    public resource.EnemyBulletResource GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public resource.EnemyBulletResource Get(int key) => _dataMap[key];
    public resource.EnemyBulletResource this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

