
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.cfgObj
{
/// <summary>
/// GM表
/// </summary>
public partial class GmObj
{
    private readonly System.Collections.Generic.Dictionary<int, resource.GMResource> _dataMap;
    private readonly System.Collections.Generic.List<resource.GMResource> _dataList;
    
    public GmObj(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, resource.GMResource>();
        _dataList = new System.Collections.Generic.List<resource.GMResource>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            resource.GMResource _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.resource.GMResource.DeserializeGMResource(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, resource.GMResource> DataMap => _dataMap;
    public System.Collections.Generic.List<resource.GMResource> DataList => _dataList;

    public resource.GMResource GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public resource.GMResource Get(int key) => _dataMap[key];
    public resource.GMResource this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

