
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.cfgObj
{
/// <summary>
/// 玩家飞机类型配置表
/// </summary>
public partial class PlayerAircraftObj
{
    private readonly System.Collections.Generic.Dictionary<int, resource.PlayerAircraftResource> _dataMap;
    private readonly System.Collections.Generic.List<resource.PlayerAircraftResource> _dataList;
    
    public PlayerAircraftObj(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, resource.PlayerAircraftResource>();
        _dataList = new System.Collections.Generic.List<resource.PlayerAircraftResource>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            resource.PlayerAircraftResource _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.resource.PlayerAircraftResource.DeserializePlayerAircraftResource(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, resource.PlayerAircraftResource> DataMap => _dataMap;
    public System.Collections.Generic.List<resource.PlayerAircraftResource> DataList => _dataList;

    public resource.PlayerAircraftResource GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public resource.PlayerAircraftResource Get(int key) => _dataMap[key];
    public resource.PlayerAircraftResource this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

