
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.cfgObj
{
/// <summary>
/// 雷电关卡配置表
/// </summary>
public partial class StageObj
{
    private readonly System.Collections.Generic.Dictionary<int, resource.StageResource> _dataMap;
    private readonly System.Collections.Generic.List<resource.StageResource> _dataList;
    
    public StageObj(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, resource.StageResource>();
        _dataList = new System.Collections.Generic.List<resource.StageResource>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            resource.StageResource _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.resource.StageResource.DeserializeStageResource(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, resource.StageResource> DataMap => _dataMap;
    public System.Collections.Generic.List<resource.StageResource> DataList => _dataList;

    public resource.StageResource GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public resource.StageResource Get(int key) => _dataMap[key];
    public resource.StageResource this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

