
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.cfgObj
{
/// <summary>
/// 雷电关卡波次配置表
/// </summary>
public partial class StageWaveObj
{
    private readonly System.Collections.Generic.Dictionary<int, resource.StageWaveResource> _dataMap;
    private readonly System.Collections.Generic.List<resource.StageWaveResource> _dataList;
    
    public StageWaveObj(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, resource.StageWaveResource>();
        _dataList = new System.Collections.Generic.List<resource.StageWaveResource>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            resource.StageWaveResource _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.resource.StageWaveResource.DeserializeStageWaveResource(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, resource.StageWaveResource> DataMap => _dataMap;
    public System.Collections.Generic.List<resource.StageWaveResource> DataList => _dataList;

    public resource.StageWaveResource GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public resource.StageWaveResource Get(int key) => _dataMap[key];
    public resource.StageWaveResource this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

