
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.resource
{
public sealed partial class EffectResource : Luban.BeanBase
{
    public EffectResource(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["code"].IsString) { throw new SerializationException(); }  Code = _buf["code"]; }
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = (EffectType)_buf["type"].AsInt; }
        { if(!_buf["res"].IsString) { throw new SerializationException(); }  Res = _buf["res"]; }
    }

    public static EffectResource DeserializeEffectResource(JSONNode _buf)
    {
        return new resource.EffectResource(_buf);
    }

    /// <summary>
    /// 特效ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 稳定编码
    /// </summary>
    public readonly string Code;
    /// <summary>
    /// 特效类型
    /// </summary>
    public readonly EffectType Type;
    /// <summary>
    /// 特效资源名
    /// </summary>
    public readonly string Res;
   
    public const int __ID__ = 1630044863;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "code:" + Code + ","
        + "type:" + Type + ","
        + "res:" + Res + ","
        + "}";
    }
}

}

