
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.resource
{
public sealed partial class PlayerAircraftResource : Luban.BeanBase
{
    public PlayerAircraftResource(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["code"].IsString) { throw new SerializationException(); }  Code = _buf["code"]; }
        { if(!_buf["displayName"].IsString) { throw new SerializationException(); }  DisplayName = _buf["displayName"]; }
        { if(!_buf["maxLevel"].IsNumber) { throw new SerializationException(); }  MaxLevel = _buf["maxLevel"]; }
        { if(!_buf["defaultUnlocked"].IsBoolean) { throw new SerializationException(); }  DefaultUnlocked = _buf["defaultUnlocked"]; }
        { if(!_buf["unlockStarCost"].IsNumber) { throw new SerializationException(); }  UnlockStarCost = _buf["unlockStarCost"]; }
    }

    public static PlayerAircraftResource DeserializePlayerAircraftResource(JSONNode _buf)
    {
        return new resource.PlayerAircraftResource(_buf);
    }

    /// <summary>
    /// 飞机类型ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 稳定编码
    /// </summary>
    public readonly string Code;
    /// <summary>
    /// 显示名称
    /// </summary>
    public readonly string DisplayName;
    /// <summary>
    /// 等级上限
    /// </summary>
    public readonly int MaxLevel;
    /// <summary>
    /// 默认解锁
    /// </summary>
    public readonly bool DefaultUnlocked;
    /// <summary>
    /// 解锁星数
    /// </summary>
    public readonly int UnlockStarCost;
   
    public const int __ID__ = 2109511749;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "code:" + Code + ","
        + "displayName:" + DisplayName + ","
        + "maxLevel:" + MaxLevel + ","
        + "defaultUnlocked:" + DefaultUnlocked + ","
        + "unlockStarCost:" + UnlockStarCost + ","
        + "}";
    }
}

}

