
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.resource
{
public sealed partial class SceneBgResource : Luban.BeanBase
{
    public SceneBgResource(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["backgroundRes"].IsString) { throw new SerializationException(); }  BackgroundRes = _buf["backgroundRes"]; }
        { if(!_buf["backgroundScrollSpeed"].IsNumber) { throw new SerializationException(); }  BackgroundScrollSpeed = _buf["backgroundScrollSpeed"]; }
        { if(!_buf["lowRes"].IsString) { throw new SerializationException(); }  LowRes = _buf["lowRes"]; }
        { if(!_buf["lowScrollSpeed"].IsNumber) { throw new SerializationException(); }  LowScrollSpeed = _buf["lowScrollSpeed"]; }
        { if(!_buf["middleRes"].IsString) { throw new SerializationException(); }  MiddleRes = _buf["middleRes"]; }
        { if(!_buf["middleScrollSpeed"].IsNumber) { throw new SerializationException(); }  MiddleScrollSpeed = _buf["middleScrollSpeed"]; }
        { if(!_buf["highRes"].IsString) { throw new SerializationException(); }  HighRes = _buf["highRes"]; }
        { if(!_buf["highScrollSpeed"].IsNumber) { throw new SerializationException(); }  HighScrollSpeed = _buf["highScrollSpeed"]; }
    }

    public static SceneBgResource DeserializeSceneBgResource(JSONNode _buf)
    {
        return new resource.SceneBgResource(_buf);
    }

    /// <summary>
    /// 场景ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 远景地表资源
    /// </summary>
    public readonly string BackgroundRes;
    /// <summary>
    /// 地表滚动速度
    /// </summary>
    public readonly float BackgroundScrollSpeed;
    /// <summary>
    /// 低空资源
    /// </summary>
    public readonly string LowRes;
    /// <summary>
    /// 低空滚动速度
    /// </summary>
    public readonly float LowScrollSpeed;
    /// <summary>
    /// 中空资源
    /// </summary>
    public readonly string MiddleRes;
    /// <summary>
    /// 中空滚动速度
    /// </summary>
    public readonly float MiddleScrollSpeed;
    /// <summary>
    /// 高空资源
    /// </summary>
    public readonly string HighRes;
    /// <summary>
    /// 高空滚动速度
    /// </summary>
    public readonly float HighScrollSpeed;
   
    public const int __ID__ = 1749766943;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "backgroundRes:" + BackgroundRes + ","
        + "backgroundScrollSpeed:" + BackgroundScrollSpeed + ","
        + "lowRes:" + LowRes + ","
        + "lowScrollSpeed:" + LowScrollSpeed + ","
        + "middleRes:" + MiddleRes + ","
        + "middleScrollSpeed:" + MiddleScrollSpeed + ","
        + "highRes:" + HighRes + ","
        + "highScrollSpeed:" + HighScrollSpeed + ","
        + "}";
    }
}

}

