
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.resource
{
public sealed partial class AircraftFireRuleResource : Luban.BeanBase
{
    public AircraftFireRuleResource(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["aircraftSizeType"].IsNumber) { throw new SerializationException(); }  AircraftSizeType = (AircraftSizeType)_buf["aircraftSizeType"].AsInt; }
        { if(!_buf["healthRateMin"].IsNumber) { throw new SerializationException(); }  HealthRateMin = _buf["healthRateMin"]; }
        { if(!_buf["healthRateMax"].IsNumber) { throw new SerializationException(); }  HealthRateMax = _buf["healthRateMax"]; }
        { var __json0 = _buf["firePointList"]; if(!__json0.IsArray) { throw new SerializationException(); } FirePointList = new System.Collections.Generic.List<AircraftFirePointCount>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { AircraftFirePointCount __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.AircraftFirePointCount.DeserializeAircraftFirePointCount(__e0);  }  FirePointList.Add(__v0); }   }
    }

    public static AircraftFireRuleResource DeserializeAircraftFireRuleResource(JSONNode _buf)
    {
        return new resource.AircraftFireRuleResource(_buf);
    }

    /// <summary>
    /// 配置ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 飞机体型
    /// </summary>
    public readonly AircraftSizeType AircraftSizeType;
    /// <summary>
    /// 血量比例下限（不含）
    /// </summary>
    public readonly int HealthRateMin;
    /// <summary>
    /// 血量比例上限（包含）
    /// </summary>
    public readonly int HealthRateMax;
    /// <summary>
    /// 着火点组合
    /// </summary>
    public readonly System.Collections.Generic.List<AircraftFirePointCount> FirePointList;
   
    public const int __ID__ = -1789366858;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in FirePointList) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "aircraftSizeType:" + AircraftSizeType + ","
        + "healthRateMin:" + HealthRateMin + ","
        + "healthRateMax:" + HealthRateMax + ","
        + "firePointList:" + Luban.StringUtil.CollectionToString(FirePointList) + ","
        + "}";
    }
}

}

