
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.resource
{
public sealed partial class AttributeResource : Luban.BeanBase
{
    public AttributeResource(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsNumber) { throw new SerializationException(); }  Name = (AttributeType)_buf["name"].AsInt; }
        { if(!_buf["valueType"].IsNumber) { throw new SerializationException(); }  ValueType = (AttributeValueFormat)_buf["valueType"].AsInt; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
    }

    public static AttributeResource DeserializeAttributeResource(JSONNode _buf)
    {
        return new resource.AttributeResource(_buf);
    }

    public readonly int Id;
    /// <summary>
    /// 属性名称
    /// </summary>
    public readonly AttributeType Name;
    /// <summary>
    /// 数值类型
    /// </summary>
    public readonly AttributeValueFormat ValueType;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
   
    public const int __ID__ = 1791390922;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "valueType:" + ValueType + ","
        + "desc:" + Desc + ","
        + "}";
    }
}

}

