
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.resource
{
public sealed partial class BulletResource : Luban.BeanBase
{
    public BulletResource(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["code"].IsString) { throw new SerializationException(); }  Code = _buf["code"]; }
        { if(!_buf["bullet"].IsObject) { throw new SerializationException(); }  Bullet = global::cfg.Bullet.DeserializeBullet(_buf["bullet"]);  }
        { if(!_buf["poolCapacity"].IsNumber) { throw new SerializationException(); }  PoolCapacity = _buf["poolCapacity"]; }
    }

    public static BulletResource DeserializeBulletResource(JSONNode _buf)
    {
        return new resource.BulletResource(_buf);
    }

    /// <summary>
    /// 子弹ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 稳定编码
    /// </summary>
    public readonly string Code;
    /// <summary>
    /// 子弹本体
    /// </summary>
    public readonly Bullet Bullet;
    /// <summary>
    /// 对象池容量
    /// </summary>
    public readonly int PoolCapacity;
   
    public const int __ID__ = -566612688;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Bullet?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "code:" + Code + ","
        + "bullet:" + Bullet + ","
        + "poolCapacity:" + PoolCapacity + ","
        + "}";
    }
}

}

