
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.resource
{
public sealed partial class ConfigValueResource : Luban.BeanBase
{
    public ConfigValueResource(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = (ConfigValueType)_buf["type"].AsInt; }
        { if(!_buf["valueType"].IsNumber) { throw new SerializationException(); }  ValueType = (ConfigValueFormat)_buf["valueType"].AsInt; }
        { if(!_buf["content"].IsString) { throw new SerializationException(); }  Content = _buf["content"]; }
    }

    public static ConfigValueResource DeserializeConfigValueResource(JSONNode _buf)
    {
        return new resource.ConfigValueResource(_buf);
    }

    public readonly int Id;
    /// <summary>
    /// 内容格式
    /// </summary>
    public readonly ConfigValueType Type;
    /// <summary>
    /// 值格式
    /// </summary>
    public readonly ConfigValueFormat ValueType;
    /// <summary>
    /// 内容
    /// </summary>
    public readonly string Content;
   
    public const int __ID__ = 363380349;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "type:" + Type + ","
        + "valueType:" + ValueType + ","
        + "content:" + Content + ","
        + "}";
    }
}

}

