
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.resource
{
public sealed partial class EnemyBulletResource : Luban.BeanBase
{
    public EnemyBulletResource(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["appearanceName"].IsString) { throw new SerializationException(); }  AppearanceName = _buf["appearanceName"]; }
        { if(!_buf["displaySize"].IsObject) { throw new SerializationException(); }  DisplaySize = global::cfg.vector2.Deserializevector2(_buf["displaySize"]);  }
        { if(!_buf["hitSize"].IsObject) { throw new SerializationException(); }  HitSize = global::cfg.vector2.Deserializevector2(_buf["hitSize"]);  }
        { if(!_buf["speed"].IsNumber) { throw new SerializationException(); }  Speed = _buf["speed"]; }
        { if(!_buf["damage"].IsNumber) { throw new SerializationException(); }  Damage = _buf["damage"]; }
        { if(!_buf["poolCapacity"].IsNumber) { throw new SerializationException(); }  PoolCapacity = _buf["poolCapacity"]; }
    }

    public static EnemyBulletResource DeserializeEnemyBulletResource(JSONNode _buf)
    {
        return new resource.EnemyBulletResource(_buf);
    }

    /// <summary>
    /// 子弹ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 外观资源名
    /// </summary>
    public readonly string AppearanceName;
    /// <summary>
    /// 显示尺寸
    /// </summary>
    public readonly vector2 DisplaySize;
    /// <summary>
    /// 碰撞尺寸
    /// </summary>
    public readonly vector2 HitSize;
    /// <summary>
    /// 飞行速度
    /// </summary>
    public readonly float Speed;
    /// <summary>
    /// 伤害
    /// </summary>
    public readonly int Damage;
    /// <summary>
    /// 对象池容量
    /// </summary>
    public readonly int PoolCapacity;
   
    public const int __ID__ = -603736360;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "appearanceName:" + AppearanceName + ","
        + "displaySize:" + DisplaySize + ","
        + "hitSize:" + HitSize + ","
        + "speed:" + Speed + ","
        + "damage:" + Damage + ","
        + "poolCapacity:" + PoolCapacity + ","
        + "}";
    }
}

}

