
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.resource
{
public sealed partial class EnemyResource : Luban.BeanBase
{
    public EnemyResource(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["enemyClass"].IsNumber) { throw new SerializationException(); }  EnemyClass = (EnemyClass)_buf["enemyClass"].AsInt; }
        { if(!_buf["displaySize"].IsObject) { throw new SerializationException(); }  DisplaySize = global::cfg.vector2.Deserializevector2(_buf["displaySize"]);  }
        { if(!_buf["fireInterval"].IsNumber) { throw new SerializationException(); }  FireInterval = _buf["fireInterval"]; }
        { if(!_buf["fireType"].IsNumber) { throw new SerializationException(); }  FireType = (EnemyFireType)_buf["fireType"].AsInt; }
        { if(!_buf["bulletId"].IsNumber) { throw new SerializationException(); }  BulletId = _buf["bulletId"]; }
        { if(!_buf["score"].IsNumber) { throw new SerializationException(); }  Score = _buf["score"]; }
        { if(!_buf["poolCapacity"].IsNumber) { throw new SerializationException(); }  PoolCapacity = _buf["poolCapacity"]; }
        { if(!_buf["aircraft"].IsObject) { throw new SerializationException(); }  Aircraft = global::cfg.Aircraft.DeserializeAircraft(_buf["aircraft"]);  }
    }

    public static EnemyResource DeserializeEnemyResource(JSONNode _buf)
    {
        return new resource.EnemyResource(_buf);
    }

    /// <summary>
    /// 敌机ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 敌机类别
    /// </summary>
    public readonly EnemyClass EnemyClass;
    /// <summary>
    /// 显示尺寸
    /// </summary>
    public readonly vector2 DisplaySize;
    /// <summary>
    /// 开火间隔
    /// </summary>
    public readonly float FireInterval;
    /// <summary>
    /// 射击模式
    /// </summary>
    public readonly EnemyFireType FireType;
    /// <summary>
    /// 子弹ID
    /// </summary>
    public readonly int BulletId;
    /// <summary>
    /// 击毁分数
    /// </summary>
    public readonly int Score;
    /// <summary>
    /// 对象池容量
    /// </summary>
    public readonly int PoolCapacity;
    /// <summary>
    /// 飞机实体
    /// </summary>
    public readonly Aircraft Aircraft;
   
    public const int __ID__ = 2124606902;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Aircraft?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "enemyClass:" + EnemyClass + ","
        + "displaySize:" + DisplaySize + ","
        + "fireInterval:" + FireInterval + ","
        + "fireType:" + FireType + ","
        + "bulletId:" + BulletId + ","
        + "score:" + Score + ","
        + "poolCapacity:" + PoolCapacity + ","
        + "aircraft:" + Aircraft + ","
        + "}";
    }
}

}

