
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.resource
{
public sealed partial class GMResource : Luban.BeanBase
{
    public GMResource(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["content"].IsString) { throw new SerializationException(); }  Content = _buf["content"]; }
        { var __json0 = _buf["paramFormat"]; if(!__json0.IsArray) { throw new SerializationException(); } ParamFormat = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  ParamFormat.Add(__v0); }   }
        { var __json0 = _buf["paramIntro"]; if(!__json0.IsArray) { throw new SerializationException(); } ParamIntro = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  ParamIntro.Add(__v0); }   }
    }

    public static GMResource DeserializeGMResource(JSONNode _buf)
    {
        return new resource.GMResource(_buf);
    }

    public readonly int Id;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Content;
    /// <summary>
    /// 参数
    /// </summary>
    public readonly System.Collections.Generic.List<string> ParamFormat;
    /// <summary>
    /// 参数说明
    /// </summary>
    public readonly System.Collections.Generic.List<string> ParamIntro;
   
    public const int __ID__ = 593154292;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "desc:" + Desc + ","
        + "content:" + Content + ","
        + "paramFormat:" + Luban.StringUtil.CollectionToString(ParamFormat) + ","
        + "paramIntro:" + Luban.StringUtil.CollectionToString(ParamIntro) + ","
        + "}";
    }
}

}

