
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.resource
{
public sealed partial class PlayerAircraftLevelResource : Luban.BeanBase
{
    public PlayerAircraftLevelResource(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["aircraftId"].IsNumber) { throw new SerializationException(); }  AircraftId = _buf["aircraftId"]; }
        { if(!_buf["level"].IsNumber) { throw new SerializationException(); }  Level = _buf["level"]; }
        { if(!_buf["displaySize"].IsObject) { throw new SerializationException(); }  DisplaySize = global::cfg.vector2.Deserializevector2(_buf["displaySize"]);  }
        { if(!_buf["baseBulletCount"].IsNumber) { throw new SerializationException(); }  BaseBulletCount = _buf["baseBulletCount"]; }
        { if(!_buf["basePower"].IsNumber) { throw new SerializationException(); }  BasePower = _buf["basePower"]; }
        { if(!_buf["aircraft"].IsObject) { throw new SerializationException(); }  Aircraft = global::cfg.Aircraft.DeserializeAircraft(_buf["aircraft"]);  }
    }

    public static PlayerAircraftLevelResource DeserializePlayerAircraftLevelResource(JSONNode _buf)
    {
        return new resource.PlayerAircraftLevelResource(_buf);
    }

    /// <summary>
    /// 等级配置ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 飞机类型ID
    /// </summary>
    public readonly int AircraftId;
    /// <summary>
    /// 等级
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 显示尺寸
    /// </summary>
    public readonly vector2 DisplaySize;
    /// <summary>
    /// 基础发射数量
    /// </summary>
    public readonly int BaseBulletCount;
    /// <summary>
    /// 基础战力
    /// </summary>
    public readonly int BasePower;
    /// <summary>
    /// 飞机实体
    /// </summary>
    public readonly Aircraft Aircraft;
   
    public const int __ID__ = -2141964837;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Aircraft?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "aircraftId:" + AircraftId + ","
        + "level:" + Level + ","
        + "displaySize:" + DisplaySize + ","
        + "baseBulletCount:" + BaseBulletCount + ","
        + "basePower:" + BasePower + ","
        + "aircraft:" + Aircraft + ","
        + "}";
    }
}

}

