
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.resource
{
public sealed partial class StageWaveResource : Luban.BeanBase
{
    public StageWaveResource(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["enemyId"].IsNumber) { throw new SerializationException(); }  EnemyId = _buf["enemyId"]; }
        { if(!_buf["motionType"].IsNumber) { throw new SerializationException(); }  MotionType = (EnemyMotionType)_buf["motionType"].AsInt; }
        { if(!_buf["formationType"].IsNumber) { throw new SerializationException(); }  FormationType = (EnemyFormationType)_buf["formationType"].AsInt; }
        { if(!_buf["enemyCount"].IsNumber) { throw new SerializationException(); }  EnemyCount = _buf["enemyCount"]; }
        { if(!_buf["spawnCenter"].IsObject) { throw new SerializationException(); }  SpawnCenter = global::cfg.vector2.Deserializevector2(_buf["spawnCenter"]);  }
        { if(!_buf["spacing"].IsNumber) { throw new SerializationException(); }  Spacing = _buf["spacing"]; }
        { if(!_buf["motionDirection"].IsNumber) { throw new SerializationException(); }  MotionDirection = _buf["motionDirection"]; }
    }

    public static StageWaveResource DeserializeStageWaveResource(JSONNode _buf)
    {
        return new resource.StageWaveResource(_buf);
    }

    /// <summary>
    /// 波次ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 敌机ID
    /// </summary>
    public readonly int EnemyId;
    /// <summary>
    /// 运动轨迹
    /// </summary>
    public readonly EnemyMotionType MotionType;
    /// <summary>
    /// 编队分布方式
    /// </summary>
    public readonly EnemyFormationType FormationType;
    /// <summary>
    /// 编队敌机数量
    /// </summary>
    public readonly int EnemyCount;
    /// <summary>
    /// 出生中心
    /// </summary>
    public readonly vector2 SpawnCenter;
    /// <summary>
    /// 成员间距
    /// </summary>
    public readonly float Spacing;
    /// <summary>
    /// 运动方向
    /// </summary>
    public readonly float MotionDirection;
   
    public const int __ID__ = -286377403;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "enemyId:" + EnemyId + ","
        + "motionType:" + MotionType + ","
        + "formationType:" + FormationType + ","
        + "enemyCount:" + EnemyCount + ","
        + "spawnCenter:" + SpawnCenter + ","
        + "spacing:" + Spacing + ","
        + "motionDirection:" + MotionDirection + ","
        + "}";
    }
}

}

