
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.resource
{
public sealed partial class StageItemResource : Luban.BeanBase
{
    public StageItemResource(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["effectType"].IsNumber) { throw new SerializationException(); }  EffectType = (StageItemEffectType)_buf["effectType"].AsInt; }
        { if(!_buf["res"].IsString) { throw new SerializationException(); }  Res = _buf["res"]; }
        { if(!_buf["collisionRadius"].IsNumber) { throw new SerializationException(); }  CollisionRadius = _buf["collisionRadius"]; }
        { if(!_buf["moveSpeed"].IsNumber) { throw new SerializationException(); }  MoveSpeed = _buf["moveSpeed"]; }
        { if(!_buf["effectValue"].IsNumber) { throw new SerializationException(); }  EffectValue = _buf["effectValue"]; }
        { if(!_buf["effectId"].IsNumber) { throw new SerializationException(); }  EffectId = _buf["effectId"]; }
        { if(!_buf["bounceDurationMs"].IsNumber) { throw new SerializationException(); }  BounceDurationMs = _buf["bounceDurationMs"]; }
        { if(!_buf["pickupText"].IsString) { throw new SerializationException(); }  PickupText = _buf["pickupText"]; }
    }

    public static StageItemResource DeserializeStageItemResource(JSONNode _buf)
    {
        return new resource.StageItemResource(_buf);
    }

    /// <summary>
    /// 关卡道具ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 拾取效果类型
    /// </summary>
    public readonly StageItemEffectType EffectType;
    /// <summary>
    /// 外观资源名
    /// </summary>
    public readonly string Res;
    /// <summary>
    /// 拾取碰撞半径
    /// </summary>
    public readonly float CollisionRadius;
    /// <summary>
    /// 飘落速度
    /// </summary>
    public readonly float MoveSpeed;
    /// <summary>
    /// 生效数值
    /// </summary>
    public readonly int EffectValue;
    /// <summary>
    /// 循环播放特效ID
    /// </summary>
    public readonly int EffectId;
    /// <summary>
    /// 边缘反弹持续时间（毫秒）
    /// </summary>
    public readonly int BounceDurationMs;
    /// <summary>
    /// 拾取飘字内容
    /// </summary>
    public readonly string PickupText;
   
    public const int __ID__ = -109877153;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "effectType:" + EffectType + ","
        + "res:" + Res + ","
        + "collisionRadius:" + CollisionRadius + ","
        + "moveSpeed:" + MoveSpeed + ","
        + "effectValue:" + EffectValue + ","
        + "effectId:" + EffectId + ","
        + "bounceDurationMs:" + BounceDurationMs + ","
        + "pickupText:" + PickupText + ","
        + "}";
    }
}

}

