
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.resource
{
public sealed partial class StageWaveResource : Luban.BeanBase
{
    public StageWaveResource(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["enemyId"].IsNumber) { throw new SerializationException(); }  EnemyId = _buf["enemyId"]; }
        { if(!_buf["motionType"].IsNumber) { throw new SerializationException(); }  MotionType = (EnemyMotionType)_buf["motionType"].AsInt; }
        { if(!_buf["formationType"].IsNumber) { throw new SerializationException(); }  FormationType = (EnemyFormationType)_buf["formationType"].AsInt; }
        { if(!_buf["enemyCount"].IsNumber) { throw new SerializationException(); }  EnemyCount = _buf["enemyCount"]; }
        { if(!_buf["spawnCenter"].IsObject) { throw new SerializationException(); }  SpawnCenter = global::cfg.vector2.Deserializevector2(_buf["spawnCenter"]);  }
        { if(!_buf["spacing"].IsNumber) { throw new SerializationException(); }  Spacing = _buf["spacing"]; }
        { if(!_buf["motionDirection"].IsNumber) { throw new SerializationException(); }  MotionDirection = _buf["motionDirection"]; }
        { if(!_buf["entrySpeedMultiplier"].IsNumber) { throw new SerializationException(); }  EntrySpeedMultiplier = _buf["entrySpeedMultiplier"]; }
        { if(!_buf["prepareDurationMs"].IsNumber) { throw new SerializationException(); }  PrepareDurationMs = _buf["prepareDurationMs"]; }
        { if(!_buf["attackDurationMs"].IsNumber) { throw new SerializationException(); }  AttackDurationMs = _buf["attackDurationMs"]; }
        { if(!_buf["patrolAmplitude"].IsNumber) { throw new SerializationException(); }  PatrolAmplitude = _buf["patrolAmplitude"]; }
        { if(!_buf["stationHeightRatio"].IsNumber) { throw new SerializationException(); }  StationHeightRatio = _buf["stationHeightRatio"]; }
        { if(!_buf["exitDirection"].IsObject) { throw new SerializationException(); }  ExitDirection = global::cfg.vector2.Deserializevector2(_buf["exitDirection"]);  }
        { if(!_buf["rewardItemId"].IsNumber) { throw new SerializationException(); }  RewardItemId = _buf["rewardItemId"]; }
    }

    public static StageWaveResource DeserializeStageWaveResource(JSONNode _buf)
    {
        return new resource.StageWaveResource(_buf);
    }

    /// <summary>
    /// 波次ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 敌机ID
    /// </summary>
    public readonly int EnemyId;
    /// <summary>
    /// 运动轨迹
    /// </summary>
    public readonly EnemyMotionType MotionType;
    /// <summary>
    /// 编队分布方式
    /// </summary>
    public readonly EnemyFormationType FormationType;
    /// <summary>
    /// 编队敌机数量
    /// </summary>
    public readonly int EnemyCount;
    /// <summary>
    /// 出生中心
    /// </summary>
    public readonly vector2 SpawnCenter;
    /// <summary>
    /// 成员间距
    /// </summary>
    public readonly float Spacing;
    /// <summary>
    /// 运动方向
    /// </summary>
    public readonly float MotionDirection;
    /// <summary>
    /// 入场速度倍率
    /// </summary>
    public readonly float EntrySpeedMultiplier;
    /// <summary>
    /// 开火准备毫秒
    /// </summary>
    public readonly int PrepareDurationMs;
    /// <summary>
    /// 攻击阶段毫秒
    /// </summary>
    public readonly int AttackDurationMs;
    /// <summary>
    /// 巡航幅度
    /// </summary>
    public readonly float PatrolAmplitude;
    /// <summary>
    /// 停留高度比例
    /// </summary>
    public readonly float StationHeightRatio;
    /// <summary>
    /// 撤离方向
    /// </summary>
    public readonly vector2 ExitDirection;
    /// <summary>
    /// 全灭奖励道具ID（0为无）
    /// </summary>
    public readonly int RewardItemId;
   
    public const int __ID__ = -286377403;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "enemyId:" + EnemyId + ","
        + "motionType:" + MotionType + ","
        + "formationType:" + FormationType + ","
        + "enemyCount:" + EnemyCount + ","
        + "spawnCenter:" + SpawnCenter + ","
        + "spacing:" + Spacing + ","
        + "motionDirection:" + MotionDirection + ","
        + "entrySpeedMultiplier:" + EntrySpeedMultiplier + ","
        + "prepareDurationMs:" + PrepareDurationMs + ","
        + "attackDurationMs:" + AttackDurationMs + ","
        + "patrolAmplitude:" + PatrolAmplitude + ","
        + "stationHeightRatio:" + StationHeightRatio + ","
        + "exitDirection:" + ExitDirection + ","
        + "rewardItemId:" + RewardItemId + ","
        + "}";
    }
}

}

