
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.resource
{
public sealed partial class StageItemResource : Luban.BeanBase
{
    public StageItemResource(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = (StageItemType)_buf["type"].AsInt; }
        { if(!_buf["res"].IsString) { throw new SerializationException(); }  Res = _buf["res"]; }
        { var __json0 = _buf["collisionShapes"]; if(!__json0.IsArray) { throw new SerializationException(); } CollisionShapes = new System.Collections.Generic.List<Shape>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { Shape __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.Shape.DeserializeShape(__e0);  }  CollisionShapes.Add(__v0); }   }
        { if(!_buf["moveSpeed"].IsNumber) { throw new SerializationException(); }  MoveSpeed = _buf["moveSpeed"]; }
        { if(!_buf["effectValue"].IsNumber) { throw new SerializationException(); }  EffectValue = _buf["effectValue"]; }
        { if(!_buf["effectId"].IsNumber) { throw new SerializationException(); }  EffectId = _buf["effectId"]; }
        { if(!_buf["swayAmplitude"].IsNumber) { throw new SerializationException(); }  SwayAmplitude = _buf["swayAmplitude"]; }
        { if(!_buf["swayPeriodMs"].IsNumber) { throw new SerializationException(); }  SwayPeriodMs = _buf["swayPeriodMs"]; }
    }

    public static StageItemResource DeserializeStageItemResource(JSONNode _buf)
    {
        return new resource.StageItemResource(_buf);
    }

    /// <summary>
    /// 关卡道具ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 道具类型
    /// </summary>
    public readonly StageItemType Type;
    /// <summary>
    /// 外观资源名
    /// </summary>
    public readonly string Res;
    /// <summary>
    /// 拾取碰撞形状列表
    /// </summary>
    public readonly System.Collections.Generic.List<Shape> CollisionShapes;
    /// <summary>
    /// 飘落速度
    /// </summary>
    public readonly float MoveSpeed;
    /// <summary>
    /// 生效数值
    /// </summary>
    public readonly int EffectValue;
    /// <summary>
    /// 循环播放特效ID
    /// </summary>
    public readonly int EffectId;
    /// <summary>
    /// 水平摆动幅度
    /// </summary>
    public readonly float SwayAmplitude;
    /// <summary>
    /// 水平摆动周期（毫秒）
    /// </summary>
    public readonly int SwayPeriodMs;
   
    public const int __ID__ = -109877153;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in CollisionShapes) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "type:" + Type + ","
        + "res:" + Res + ","
        + "collisionShapes:" + Luban.StringUtil.CollectionToString(CollisionShapes) + ","
        + "moveSpeed:" + MoveSpeed + ","
        + "effectValue:" + EffectValue + ","
        + "effectId:" + EffectId + ","
        + "swayAmplitude:" + SwayAmplitude + ","
        + "swayPeriodMs:" + SwayPeriodMs + ","
        + "}";
    }
}

}

