
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.resource
{
public sealed partial class WingmanResource : Luban.BeanBase
{
    public WingmanResource(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["code"].IsString) { throw new SerializationException(); }  Code = _buf["code"]; }
        { if(!_buf["displayName"].IsString) { throw new SerializationException(); }  DisplayName = _buf["displayName"]; }
        { if(!_buf["displaySize"].IsObject) { throw new SerializationException(); }  DisplaySize = global::cfg.vector2.Deserializevector2(_buf["displaySize"]);  }
        { if(!_buf["maxCount"].IsNumber) { throw new SerializationException(); }  MaxCount = _buf["maxCount"]; }
        { if(!_buf["formationType"].IsNumber) { throw new SerializationException(); }  FormationType = (WingmanFormationType)_buf["formationType"].AsInt; }
        { var __json0 = _buf["formationOffsets"]; if(!__json0.IsArray) { throw new SerializationException(); } FormationOffsets = new System.Collections.Generic.List<vector2>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { vector2 __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.vector2.Deserializevector2(__e0);  }  FormationOffsets.Add(__v0); }   }
        { if(!_buf["followSpeed"].IsNumber) { throw new SerializationException(); }  FollowSpeed = _buf["followSpeed"]; }
        { if(!_buf["unit"].IsObject) { throw new SerializationException(); }  Unit = global::cfg.FlyingUnit.DeserializeFlyingUnit(_buf["unit"]);  }
    }

    public static WingmanResource DeserializeWingmanResource(JSONNode _buf)
    {
        return new resource.WingmanResource(_buf);
    }

    /// <summary>
    /// 僚机类型ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 稳定编码
    /// </summary>
    public readonly string Code;
    /// <summary>
    /// 显示名称
    /// </summary>
    public readonly string DisplayName;
    /// <summary>
    /// 显示尺寸
    /// </summary>
    public readonly vector2 DisplaySize;
    /// <summary>
    /// 关卡内数量上限
    /// </summary>
    public readonly int MaxCount;
    /// <summary>
    /// 编队方式
    /// </summary>
    public readonly WingmanFormationType FormationType;
    /// <summary>
    /// 编队槽位坐标列表
    /// </summary>
    public readonly System.Collections.Generic.List<vector2> FormationOffsets;
    /// <summary>
    /// 跟随速度
    /// </summary>
    public readonly float FollowSpeed;
    /// <summary>
    /// 飞行单位
    /// </summary>
    public readonly FlyingUnit Unit;
   
    public const int __ID__ = -1852523363;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Unit?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "code:" + Code + ","
        + "displayName:" + DisplayName + ","
        + "displaySize:" + DisplaySize + ","
        + "maxCount:" + MaxCount + ","
        + "formationType:" + FormationType + ","
        + "formationOffsets:" + Luban.StringUtil.CollectionToString(FormationOffsets) + ","
        + "followSpeed:" + FollowSpeed + ","
        + "unit:" + Unit + ","
        + "}";
    }
}

}

