
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 飞机体型
    /// </summary>
    public enum AircraftSizeType
    {
        /// <summary>
        /// 小型
        /// </summary>
        SMALL = 1,
        /// <summary>
        /// 中型
        /// </summary>
        MEDIUM = 2,
        /// <summary>
        /// 大型
        /// </summary>
        LARGE = 3,
        /// <summary>
        /// 巨型
        /// </summary>
        GIANT = 4,
    }

} 

