
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 属性值格式
    /// </summary>
    public enum AttributeValueFormat
    {
        /// <summary>
        /// 绝对值
        /// </summary>
        VALUE = 0,
        /// <summary>
        /// 表示万分比的整数值
        /// </summary>
        RATE = 1,
    }

} 

