
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 属性配置项及其基础数值
/// </summary>
public sealed partial class AttributeValue : Luban.BeanBase
{
    public AttributeValue(JSONNode _buf) 
    {
        { if(!_buf["attributeId"].IsNumber) { throw new SerializationException(); }  AttributeId = (AttributeType)_buf["attributeId"].AsInt; }
        { if(!_buf["value"].IsNumber) { throw new SerializationException(); }  Value = _buf["value"]; }
    }

    public static AttributeValue DeserializeAttributeValue(JSONNode _buf)
    {
        return new AttributeValue(_buf);
    }

    /// <summary>
    /// 属性表 ID
    /// </summary>
    public readonly AttributeType AttributeId;
    /// <summary>
    /// 属性基础值
    /// </summary>
    public readonly int Value;
   
    public const int __ID__ = 1322714197;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "attributeId:" + AttributeId + ","
        + "value:" + Value + ","
        + "}";
    }
}

}

