
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 子弹散布方式
    /// </summary>
    public enum BulletSpreadType
    {
        /// <summary>
        /// 基于发射器朝向向两侧均匀分布
        /// </summary>
        CENTERED = 0,
        /// <summary>
        /// 基于发射器朝向向左侧均匀分布
        /// </summary>
        LEFT = 1,
        /// <summary>
        /// 基于发射器朝向向右侧均匀分布
        /// </summary>
        RIGHT = 2,
    }

} 

