
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 常量数据类型
    /// </summary>
    public enum ConfigValueType
    {
        /// <summary>
        /// 普通
        /// </summary>
        NORMAL = 0,
        /// <summary>
        /// 列表
        /// </summary>
        LIST = 1,
        /// <summary>
        /// Map
        /// </summary>
        MAP = 2,
    }

} 

