
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 常量数据值格式
    /// </summary>
    public enum ConfigValueFormat
    {
        /// <summary>
        /// 字符串
        /// </summary>
        STRING = 0,
        /// <summary>
        /// 整数
        /// </summary>
        INT = 1,
        /// <summary>
        /// 浮点数
        /// </summary>
        FLOAT = 2,
    }

} 

