
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 定义飞机死亡表现中的单个爆炸效果
/// </summary>
public sealed partial class ExplosionEffect : Luban.BeanBase
{
    public ExplosionEffect(JSONNode _buf) 
    {
        { if(!_buf["delayMs"].IsNumber) { throw new SerializationException(); }  DelayMs = _buf["delayMs"]; }
        { if(!_buf["position"].IsObject) { throw new SerializationException(); }  Position = global::cfg.vector2.Deserializevector2(_buf["position"]);  }
        { if(!_buf["effectId"].IsNumber) { throw new SerializationException(); }  EffectId = _buf["effectId"]; }
    }

    public static ExplosionEffect DeserializeExplosionEffect(JSONNode _buf)
    {
        return new ExplosionEffect(_buf);
    }

    /// <summary>
    /// 相对飞机死亡开始时刻的延迟毫秒数
    /// </summary>
    public readonly int DelayMs;
    /// <summary>
    /// 相对飞机实体原点的播放位置
    /// </summary>
    public readonly vector2 Position;
    /// <summary>
    /// 引用特效表中的特效ID
    /// </summary>
    public readonly int EffectId;
   
    public const int __ID__ = 229846246;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "delayMs:" + DelayMs + ","
        + "position:" + Position + ","
        + "effectId:" + EffectId + ","
        + "}";
    }
}

}

