
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 关卡道具拾取效果类型
    /// </summary>
    public enum StageItemEffectType
    {
        /// <summary>
        /// 玩家升级
        /// </summary>
        PLAYER_UPGRADE = 0,
        /// <summary>
        /// 增加僚机
        /// </summary>
        ADD_WINGMAN = 1,
        /// <summary>
        /// 回血
        /// </summary>
        HEALTH = 2,
        /// <summary>
        /// 增加生命
        /// </summary>
        LIFE = 3,
        /// <summary>
        /// 弹药强化
        /// </summary>
        AMMO_BOOST = 4,
        /// <summary>
        /// 增加能量
        /// </summary>
        ENERGY_FRAGMENT = 5,
    }

} 

