
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 状态值类型
    /// </summary>
    public enum StateValueType
    {
        /// <summary>
        /// 当前生命
        /// </summary>
        LIFE = 1,
        /// <summary>
        /// 当前能量
        /// </summary>
        ENERGY = 2,
    }

} 

