
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 僚机编队方式
    /// </summary>
    public enum WingmanFormationType
    {
        /// <summary>
        /// 按玩家两侧的固定槽位排列并平滑跟随
        /// </summary>
        SIDE_BY_SIDE = 0,
        /// <summary>
        /// 围绕玩家飞机运动
        /// </summary>
        ORBIT = 1,
        /// <summary>
        /// 按预设阵型槽位排列
        /// </summary>
        FIXED_FORMATION = 2,
        /// <summary>
        /// 在视窗下半区域独立活动
        /// </summary>
        LOWER_SCREEN_FREE = 3,
    }

} 

