
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.cfgObj
{
/// <summary>
/// 普通敌机配置表
/// </summary>
public partial class EnemyObj
{
    private readonly System.Collections.Generic.Dictionary<int, resource.EnemyResource> _dataMap;
    private readonly System.Collections.Generic.List<resource.EnemyResource> _dataList;
    
    public EnemyObj(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, resource.EnemyResource>();
        _dataList = new System.Collections.Generic.List<resource.EnemyResource>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            resource.EnemyResource _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.resource.EnemyResource.DeserializeEnemyResource(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, resource.EnemyResource> DataMap => _dataMap;
    public System.Collections.Generic.List<resource.EnemyResource> DataList => _dataList;

    public resource.EnemyResource GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public resource.EnemyResource Get(int key) => _dataMap[key];
    public resource.EnemyResource this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

