
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.cfgObj
{
/// <summary>
/// 场景背景配置表
/// </summary>
public partial class SceneBgObj
{
    private readonly System.Collections.Generic.Dictionary<int, resource.SceneBgResource> _dataMap;
    private readonly System.Collections.Generic.List<resource.SceneBgResource> _dataList;
    
    public SceneBgObj(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, resource.SceneBgResource>();
        _dataList = new System.Collections.Generic.List<resource.SceneBgResource>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            resource.SceneBgResource _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.resource.SceneBgResource.DeserializeSceneBgResource(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, resource.SceneBgResource> DataMap => _dataMap;
    public System.Collections.Generic.List<resource.SceneBgResource> DataList => _dataList;

    public resource.SceneBgResource GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public resource.SceneBgResource Get(int key) => _dataMap[key];
    public resource.SceneBgResource this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

