
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.cfgObj
{
/// <summary>
/// 关卡道具配置表
/// </summary>
public partial class StageItemObj
{
    private readonly System.Collections.Generic.Dictionary<int, resource.StageItemResource> _dataMap;
    private readonly System.Collections.Generic.List<resource.StageItemResource> _dataList;
    
    public StageItemObj(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, resource.StageItemResource>();
        _dataList = new System.Collections.Generic.List<resource.StageItemResource>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            resource.StageItemResource _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.resource.StageItemResource.DeserializeStageItemResource(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, resource.StageItemResource> DataMap => _dataMap;
    public System.Collections.Generic.List<resource.StageItemResource> DataList => _dataList;

    public resource.StageItemResource GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public resource.StageItemResource Get(int key) => _dataMap[key];
    public resource.StageItemResource this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

