
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 着火规模
    /// </summary>
    public enum AircraftFireSize
    {
        /// <summary>
        /// 小
        /// </summary>
        SMALL = 1,
        /// <summary>
        /// 中
        /// </summary>
        MEDIUM = 2,
        /// <summary>
        /// 大
        /// </summary>
        LARGE = 3,
    }

} 

