
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 定义指定规模的着火点数量
/// </summary>
public sealed partial class AircraftFirePointCount : Luban.BeanBase
{
    public AircraftFirePointCount(JSONNode _buf) 
    {
        { if(!_buf["fireSize"].IsNumber) { throw new SerializationException(); }  FireSize = (AircraftFireSize)_buf["fireSize"].AsInt; }
        { if(!_buf["count"].IsNumber) { throw new SerializationException(); }  Count = _buf["count"]; }
    }

    public static AircraftFirePointCount DeserializeAircraftFirePointCount(JSONNode _buf)
    {
        return new AircraftFirePointCount(_buf);
    }

    /// <summary>
    /// 着火规模
    /// </summary>
    public readonly AircraftFireSize FireSize;
    /// <summary>
    /// 着火点数量
    /// </summary>
    public readonly int Count;
   
    public const int __ID__ = 888966411;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "fireSize:" + FireSize + ","
        + "count:" + Count + ","
        + "}";
    }
}

}

