
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 属性值类型
    /// </summary>
    public enum AttributeType
    {
        /// <summary>
        /// 最大生命值
        /// </summary>
        MAX_LIFE = 1,
        /// <summary>
        /// 速度
        /// </summary>
        SPEED = 2,
        /// <summary>
        /// 调整两轮开火之间的等待时间
        /// </summary>
        FIRE_COOLDOWN_RATE = 3,
        /// <summary>
        /// 调整同一轮内相邻子弹的发射间隔
        /// </summary>
        SHOT_INTERVAL_RATE = 4,
        /// <summary>
        /// 子弹发射数
        /// </summary>
        SHOOT_NUM = 5,
    }

} 

