
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 子弹外观类型
    /// </summary>
    public enum BulletAppearanceType
    {
        /// <summary>
        /// 图片
        /// </summary>
        IMAGE = 0,
        /// <summary>
        /// 帧动画
        /// </summary>
        FRAME_ANIMATION = 1,
    }

} 

