
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 定义子弹本体的通用战斗参数
/// </summary>
public sealed partial class Bullet : Luban.BeanBase
{
    public Bullet(JSONNode _buf) 
    {
        { if(!_buf["appearanceType"].IsNumber) { throw new SerializationException(); }  AppearanceType = (BulletAppearanceType)_buf["appearanceType"].AsInt; }
        { if(!_buf["appearancePath"].IsString) { throw new SerializationException(); }  AppearancePath = _buf["appearancePath"]; }
        { if(!_buf["shape"].IsObject) { throw new SerializationException(); }  Shape = global::cfg.Shape.DeserializeShape(_buf["shape"]);  }
        { if(!_buf["motionType"].IsNumber) { throw new SerializationException(); }  MotionType = (BulletMotionType)_buf["motionType"].AsInt; }
        { if(!_buf["rotate"].IsBoolean) { throw new SerializationException(); }  Rotate = _buf["rotate"]; }
        { if(!_buf["rotationSpeed"].IsNumber) { throw new SerializationException(); }  RotationSpeed = _buf["rotationSpeed"]; }
        { if(!_buf["speed"].IsNumber) { throw new SerializationException(); }  Speed = _buf["speed"]; }
        { if(!_buf["damage"].IsNumber) { throw new SerializationException(); }  Damage = _buf["damage"]; }
        { if(!_buf["hitEffectId"].IsNumber) { throw new SerializationException(); }  HitEffectId = _buf["hitEffectId"]; }
        { if(!_buf["trackingDelayMs"].IsNumber) { throw new SerializationException(); }  TrackingDelayMs = _buf["trackingDelayMs"]; }
        { if(!_buf["trackingTurnSpeed"].IsNumber) { throw new SerializationException(); }  TrackingTurnSpeed = _buf["trackingTurnSpeed"]; }
        { if(!_buf["launchEffectId"].IsNumber) { throw new SerializationException(); }  LaunchEffectId = _buf["launchEffectId"]; }
    }

    public static Bullet DeserializeBullet(JSONNode _buf)
    {
        return new Bullet(_buf);
    }

    /// <summary>
    /// 外观资源类型
    /// </summary>
    public readonly BulletAppearanceType AppearanceType;
    /// <summary>
    /// 外观资源相对路径
    /// </summary>
    public readonly string AppearancePath;
    /// <summary>
    /// 子弹形状信息
    /// </summary>
    public readonly Shape Shape;
    /// <summary>
    /// 行动方式
    /// </summary>
    public readonly BulletMotionType MotionType;
    /// <summary>
    /// 飞行期间是否自转
    /// </summary>
    public readonly bool Rotate;
    /// <summary>
    /// 自转速度
    /// </summary>
    public readonly float RotationSpeed;
    /// <summary>
    /// 飞行速度
    /// </summary>
    public readonly float Speed;
    /// <summary>
    /// 伤害值
    /// </summary>
    public readonly int Damage;
    /// <summary>
    /// 引用特效表中的命中特效ID
    /// </summary>
    public readonly int HitEffectId;
    /// <summary>
    /// 跟踪锁定延迟，单位毫秒；仅跟踪型生效
    /// </summary>
    public readonly int TrackingDelayMs;
    /// <summary>
    /// 跟踪转向速度，单位度/秒；仅跟踪型生效
    /// </summary>
    public readonly float TrackingTurnSpeed;
    /// <summary>
    /// 引用特效表中的发射特效ID；未配置时不播放
    /// </summary>
    public readonly int LaunchEffectId;
   
    public const int __ID__ = 2000900386;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Shape?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "appearanceType:" + AppearanceType + ","
        + "appearancePath:" + AppearancePath + ","
        + "shape:" + Shape + ","
        + "motionType:" + MotionType + ","
        + "rotate:" + Rotate + ","
        + "rotationSpeed:" + RotationSpeed + ","
        + "speed:" + Speed + ","
        + "damage:" + Damage + ","
        + "hitEffectId:" + HitEffectId + ","
        + "trackingDelayMs:" + TrackingDelayMs + ","
        + "trackingTurnSpeed:" + TrackingTurnSpeed + ","
        + "launchEffectId:" + LaunchEffectId + ","
        + "}";
    }
}

}

