
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 子弹行动类型
    /// </summary>
    public enum BulletMotionType
    {
        /// <summary>
        /// 直线
        /// </summary>
        STRAIGHT = 0,
        /// <summary>
        /// 跟踪
        /// </summary>
        TRACKING = 1,
    }

} 

