
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
/// <summary>
/// 定义实体的子弹生成逻辑
/// </summary>
public sealed partial class BulletLauncher : Luban.BeanBase
{
    public BulletLauncher(JSONNode _buf) 
    {
        { if(!_buf["offset"].IsObject) { throw new SerializationException(); }  Offset = global::cfg.vector2.Deserializevector2(_buf["offset"]);  }
        { if(!_buf["bulletId"].IsNumber) { throw new SerializationException(); }  BulletId = _buf["bulletId"]; }
        { if(!_buf["bulletCount"].IsNumber) { throw new SerializationException(); }  BulletCount = _buf["bulletCount"]; }
        { if(!_buf["fireIntervalMs"].IsNumber) { throw new SerializationException(); }  FireIntervalMs = _buf["fireIntervalMs"]; }
        { if(!_buf["bulletIntervalMs"].IsNumber) { throw new SerializationException(); }  BulletIntervalMs = _buf["bulletIntervalMs"]; }
        { if(!_buf["direction"].IsNumber) { throw new SerializationException(); }  Direction = _buf["direction"]; }
        { if(!_buf["spreadType"].IsNumber) { throw new SerializationException(); }  SpreadType = (BulletSpreadType)_buf["spreadType"].AsInt; }
        { if(!_buf["spreadAngle"].IsNumber) { throw new SerializationException(); }  SpreadAngle = _buf["spreadAngle"]; }
    }

    public static BulletLauncher DeserializeBulletLauncher(JSONNode _buf)
    {
        return new BulletLauncher(_buf);
    }

    /// <summary>
    /// 发射点相对所属实体原点的坐标
    /// </summary>
    public readonly vector2 Offset;
    /// <summary>
    /// 生成的子弹类型ID
    /// </summary>
    public readonly int BulletId;
    /// <summary>
    /// 每轮发射生成的子弹数量
    /// </summary>
    public readonly int BulletCount;
    /// <summary>
    /// 两轮发射起点之间的间隔毫秒数
    /// </summary>
    public readonly int FireIntervalMs;
    /// <summary>
    /// 同一轮内相邻子弹的生成间隔毫秒数
    /// </summary>
    public readonly int BulletIntervalMs;
    /// <summary>
    /// 发射器基准朝向角度
    /// </summary>
    public readonly float Direction;
    /// <summary>
    /// 子弹朝向的散布策略
    /// </summary>
    public readonly BulletSpreadType SpreadType;
    /// <summary>
    /// 基于发射器朝向的散布角度范围
    /// </summary>
    public readonly float SpreadAngle;
   
    public const int __ID__ = -1938652446;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "offset:" + Offset + ","
        + "bulletId:" + BulletId + ","
        + "bulletCount:" + BulletCount + ","
        + "fireIntervalMs:" + FireIntervalMs + ","
        + "bulletIntervalMs:" + BulletIntervalMs + ","
        + "direction:" + Direction + ","
        + "spreadType:" + SpreadType + ","
        + "spreadAngle:" + SpreadAngle + ","
        + "}";
    }
}

}

