
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class CircleShape : Shape
{
    public CircleShape(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["radius"].IsNumber) { throw new SerializationException(); }  Radius = _buf["radius"]; }
    }

    public static CircleShape DeserializeCircleShape(JSONNode _buf)
    {
        return new CircleShape(_buf);
    }

    /// <summary>
    /// 圆形半径
    /// </summary>
    public readonly float Radius;
   
    public const int __ID__ = 1589955729;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "radius:" + Radius + ","
        + "}";
    }
}

}

