
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 特效类型
    /// </summary>
    public enum EffectType
    {
        /// <summary>
        /// 子弹命中特效
        /// </summary>
        BULLET_HIT = 0,
        /// <summary>
        /// 飞机爆炸特效
        /// </summary>
        AIRCRAFT_EXPLOSION = 1,
        /// <summary>
        /// 通用或暂未独立分类的演出特效
        /// </summary>
        OTHER = 2,
    }

} 

