
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 特效类型
    /// </summary>
    public enum EffectType
    {
        /// <summary>
        /// 通用或暂未独立分类的演出特效
        /// </summary>
        OTHER = 0,
        /// <summary>
        /// 子弹发射
        /// </summary>
        BULLET_LAUNCH = 1,
        /// <summary>
        /// 子弹
        /// </summary>
        BULLET = 2,
        /// <summary>
        /// 子弹命中
        /// </summary>
        BULLET_HIT = 3,
        /// <summary>
        /// 爆炸
        /// </summary>
        AIRCRAFT_EXPLOSION = 4,
    }

} 

