
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 敌机类别
    /// </summary>
    public enum EnemyClass
    {
        /// <summary>
        /// 普通
        /// </summary>
        NORMAL = 0,
        /// <summary>
        /// 精英
        /// </summary>
        ELITE = 1,
        /// <summary>
        /// Boss
        /// </summary>
        BOSS = 2,
    }

} 

