
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 敌机编队分布方式
    /// </summary>
    public enum EnemyFormationType
    {
        /// <summary>
        /// 横向编队
        /// </summary>
        HORIZONTAL = 0,
        /// <summary>
        /// 斜向编队
        /// </summary>
        DIAGONAL = 1,
    }

} 

