
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 敌机射击模式
    /// </summary>
    public enum EnemyFireType
    {
        /// <summary>
        /// 单发
        /// </summary>
        SINGLE = 0,
        /// <summary>
        /// 双发
        /// </summary>
        TWIN = 1,
        /// <summary>
        /// 散射
        /// </summary>
        SPREAD = 2,
        /// <summary>
        /// 瞄准
        /// </summary>
        AIMED = 3,
    }

} 

