
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 敌机运动轨迹
    /// </summary>
    public enum EnemyMotionType
    {
        /// <summary>
        /// 直线
        /// </summary>
        STRAIGHT = 0,
        /// <summary>
        /// 斜向
        /// </summary>
        DIAGONAL = 1,
        /// <summary>
        /// 蛇形
        /// </summary>
        SNAKE = 2,
        /// <summary>
        /// 编队转向
        /// </summary>
        FORMATION_TURN = 3,
    }

} 

