
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 敌机运动轨迹
    /// </summary>
    public enum EnemyMotionType
    {
        /// <summary>
        /// 定点攻击
        /// </summary>
        STATIONARY = 0,
        /// <summary>
        /// 横向穿越
        /// </summary>
        HORIZONTAL_PASS = 2,
        /// <summary>
        /// 巡航攻击
        /// </summary>
        PATROL = 3,
    }

} 

