
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class RectangleShape : Shape
{
    public RectangleShape(JSONNode _buf)  : base(_buf) 
    {
        { if(!_buf["rect"].IsObject) { throw new SerializationException(); }  Rect = global::cfg.vector2.Deserializevector2(_buf["rect"]);  }
        { if(!_buf["pivot"].IsObject) { throw new SerializationException(); }  Pivot = global::cfg.vector2.Deserializevector2(_buf["pivot"]);  }
    }

    public static RectangleShape DeserializeRectangleShape(JSONNode _buf)
    {
        return new RectangleShape(_buf);
    }

    /// <summary>
    /// 矩形长宽
    /// </summary>
    public readonly vector2 Rect;
    /// <summary>
    /// 矩形定位点
    /// </summary>
    public readonly vector2 Pivot;
   
    public const int __ID__ = -148796526;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "rect:" + Rect + ","
        + "pivot:" + Pivot + ","
        + "}";
    }
}

}

