
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    /// <summary>
    /// 关卡道具类型
    /// </summary>
    public enum StageItemType
    {
        /// <summary>
        /// 玩家升级
        /// </summary>
        PLAYER_UPGRADE = 0,
        /// <summary>
        /// 僚机升级
        /// </summary>
        WINGMAN_UPGRADE = 1,
        /// <summary>
        /// 回血
        /// </summary>
        HEALTH = 2,
        /// <summary>
        /// 加命
        /// </summary>
        LIFE = 3,
    }

} 

