
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    /// <summary>
    /// GM表
    /// </summary>
    public cfgObj.GmObj GmObj {get; }
    /// <summary>
    /// 设置选项表
    /// </summary>
    public cfgObj.SettingOptionObj SettingOptionObj {get; }
    /// <summary>
    /// 雷电关卡配置表
    /// </summary>
    public cfgObj.StageObj StageObj {get; }
    /// <summary>
    /// 雷电关卡波次配置表
    /// </summary>
    public cfgObj.StageWaveObj StageWaveObj {get; }
    /// <summary>
    /// 普通敌机配置表
    /// </summary>
    public cfgObj.EnemyObj EnemyObj {get; }
    /// <summary>
    /// 玩家飞机类型配置表
    /// </summary>
    public cfgObj.PlayerAircraftObj PlayerAircraftObj {get; }
    /// <summary>
    /// 玩家飞机等级配置表
    /// </summary>
    public cfgObj.PlayerAircraftLevelObj PlayerAircraftLevelObj {get; }
    /// <summary>
    /// 通用子弹配置表
    /// </summary>
    public cfgObj.BulletObj BulletObj {get; }
    /// <summary>
    /// 通用特效配置表
    /// </summary>
    public cfgObj.EffectObj EffectObj {get; }
    /// <summary>
    /// 场景背景配置表
    /// </summary>
    public cfgObj.SceneBgObj SceneBgObj {get; }
    /// <summary>
    /// 关卡道具配置表
    /// </summary>
    public cfgObj.StageItemObj StageItemObj {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        GmObj = new cfgObj.GmObj(loader("cfgobj_gmobj"));
        SettingOptionObj = new cfgObj.SettingOptionObj(loader("cfgobj_settingoptionobj"));
        StageObj = new cfgObj.StageObj(loader("cfgobj_stageobj"));
        StageWaveObj = new cfgObj.StageWaveObj(loader("cfgobj_stagewaveobj"));
        EnemyObj = new cfgObj.EnemyObj(loader("cfgobj_enemyobj"));
        PlayerAircraftObj = new cfgObj.PlayerAircraftObj(loader("cfgobj_playeraircraftobj"));
        PlayerAircraftLevelObj = new cfgObj.PlayerAircraftLevelObj(loader("cfgobj_playeraircraftlevelobj"));
        BulletObj = new cfgObj.BulletObj(loader("cfgobj_bulletobj"));
        EffectObj = new cfgObj.EffectObj(loader("cfgobj_effectobj"));
        SceneBgObj = new cfgObj.SceneBgObj(loader("cfgobj_scenebgobj"));
        StageItemObj = new cfgObj.StageItemObj(loader("cfgobj_stageitemobj"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        GmObj.ResolveRef(this);
        SettingOptionObj.ResolveRef(this);
        StageObj.ResolveRef(this);
        StageWaveObj.ResolveRef(this);
        EnemyObj.ResolveRef(this);
        PlayerAircraftObj.ResolveRef(this);
        PlayerAircraftLevelObj.ResolveRef(this);
        BulletObj.ResolveRef(this);
        EffectObj.ResolveRef(this);
        SceneBgObj.ResolveRef(this);
        StageItemObj.ResolveRef(this);
    }
}

}
